### ISSUE TITLE
Improved multi-platform support

### ISSUE THREAD

**Issue by radix42** [ZcashFoundation/GrantProposals-2017Q4#21]
Having previously ported zcash to macOS, Windows and aarch64 (aka arm64), a number of impediments to support for these non-linux/x86 platforms directly in upstream zcash currently exist.

This grant proposal will be to make various improvements to support for these platforms, with the deliverables being pull requests to the various projects required for them to be integrated into the upstream codebase (at the very least against the zcash, libsnark and gmp projects). Details in the full grant proposal.

**Comment by tromer** [comment]
It would be helpful to start listing the details before the full proposal (or submit a draft full proposal much before the deadline), to allow feedback.

**Comment by acityinohio** [comment]
Every informal proposal has multiple reviews by the review committee. The reviews are being collected and discussed in a private google doc (the 5 reviewers all have edit access to it, no one else can view it). By way of early, informal feedback, the reviewers have made a list of projects that they consider leading candidates for grant funding.

In that vein, **your project was selected as one of the leading candidates**, and the review committee encourages you to submit a full proposal by **October 6th** and looks forward to reviewing it.

**Comment by radix42** [comment]
Full proposal:
[CrossPlatformGrantProposal.pdf](https://github.com/ZcashFoundation/GrantProposals-2017Q4/files/1364175/CrossPlatformGrantProposal.pdf)

**Comment by radix42** [comment]
Minor update to security section:
[CrossPlatformGrantProposal.pdf](https://github.com/ZcashFoundation/GrantProposals-2017Q4/files/1364185/CrossPlatformGrantProposal.pdf)

**Comment by radix42** [comment]
I just found out that one of the developers I work with on a zcash fork has had contact with the gmp community a lot in the past, and they've offered to tackle the "send clean patch(s) upstream to gmp" part of this project when it comes to that.

**Comment by acityinohio** [comment]
@radix42 : I'm thrilled to inform you that the Grant Review committee—and the Zcash Foundation board—has tentatively approved your proposal! While the [recommendations are already posted](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/grants/2017-Q4/Zcash-Foundation-grants-2017-Q4-recommendations.md), we are planning to make a more public post tomorrow morning (November 21st) Pacific Standard Time.

Next steps: please email me `josh [at] z.cash.foundation` with an email address suitable as a point of contact. Due to our [newfound 501(c)3 status](https://z.cash.foundation//blog/zcash-foundation-officially-nonprofit/) there are additional reporting and compliance burdens that may delay or change disbursements, but we are working through them as fast as we can.

Just in case you didn't see it, please find the committee recommendation for your project below, and congratulations again (twice over!)

> The proposer has ported the zcashd software and the Zcash desktop GUI wallet to Windows and Mac. He proposes to continue and stabilize this work by unifying the various porting branches and build scripts, deploy and maintaining machines for Mac and Windows testing environments, and preparing porting efforts for upstream merging.
> 
> The review committee consider Mac and Windows support to be important for mainstream Zcash adoption. The proposed work will significant improve the reliability and maintainability of this code, both in the ports released by the proposer and in helping the upstream developers build and test their software on those platforms.
> 
> The proposer is well known by the Zcash community (he is also running a block explorer, see #19) and is capable of following through on all work promised. Funding of the full amount is recommended.

**Comment by sonyamann** [comment]
Hi @radix42! I'm pinging all of the 2017 grant recipients for updates on their projects. I have a rough sense of the state of yours, but I wonder if you'd like to write a short official update?

I know you and @acityinohio are going to discuss a potential contract with the Foundation soon, so maybe that conversation is a more appropriate venue for an update on this grant, and then Josh can loop me in. Let me know what works best :) Thanks!

**Comment by radix42** [comment]
As of a couple of days ago the master branch of https://github.com/zcash/zcash.git and now the 2.0.1-rc1 release build on linux, mac and cross compile to Windows out of the box, so I'm closing this now!
